# Generated by Django 3.1.1 on 2020-10-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='sentence',
        ),
    ]
