# Generated by Django 3.1.5 on 2021-01-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recite', '0002_remove_words_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='is_recite',
            field=models.BooleanField(default=True, verbose_name='是否需要检测背诵'),
        ),
    ]
