# Generated by Django 3.1.1 on 2020-09-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('priority',), 'verbose_name': '文章列表', 'verbose_name_plural': '文章列表'},
        ),
        migrations.AddField(
            model_name='article',
            name='look',
            field=models.IntegerField(default=0),
        ),
    ]
