# Generated by Django 3.1.1 on 2020-09-26 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200926_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='发布日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='look',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
