# Generated by Django 3.1.1 on 2020-09-26 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objs', to='myapp.book', verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='标题'),
        ),
    ]
