# Generated by Django 3.1.1 on 2020-10-08 06:12

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200926_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='myapp.book', verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='正文'),
        ),
    ]
