# Generated by Django 3.1.1 on 2020-10-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201012_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='QQ',
            field=models.CharField(max_length=2000, verbose_name='QQ'),
        ),
    ]
