# Generated by Django 3.1.1 on 2020-10-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.TextField(default='作者暂未回复', verbose_name='作者的回复'),
        ),
    ]
