# Generated by Django 3.1.5 on 2021-01-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20201012_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.TextField(default='谢谢你支持我，评论我的博客！', verbose_name='作者的回复'),
        ),
    ]
